### ISSUE TITLE
Synapse wont run

### ISSUE THREAD

**Issue by Jmodel10** [LoukaMB/SynapseX#155]
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SX.SX_"K.SX_!(Object -*)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=z51Swmy5x9WdEHNfOgmG5B1oZv00XSFztj5YSUaI=(Exception #=z0l0hrbY=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zA1xi_20$zpkJJJiUnfA5X1Y=(Object #=z0l0hrbY=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zIjxj8Op3JOurBlqvYRvxRlw=(MethodBase #=z0l0hrbY=, Boolean #=zLCVRNWs=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=z3A2IzQVaYkLbBhTV73C9QxC1z3ZRp_4MzLn_xUw=(#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc= #=z0l0hrbY=, #=qVJb9$H33pNrwn2ekQ5xoGpSTXVbWLFPpXwFt$Ys1GiA= #=zLCVRNWs=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zPJL9GRPQPqZQEXfFObv80cMkgWbEcp1K7oB_NVk=()
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zA0pHDTueDwlCslT1lMvtrlY=(Boolean #=z0l0hrbY=)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SX.SX_"K.SX_!(Object -*)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=z51Swmy5x9WdEHNfOgmG5B1oZv00XSFztj5YSUaI=(Exception #=z0l0hrbY=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zA1xi_20$zpkJJJiUnfA5X1Y=(Object #=z0l0hrbY=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zVMagYZTr0KT3UbPw4xrLdyM=()
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zWZTD_2pkWHk5HDH7NwpusDc=(Object #=z0l0hrbY=, UInt32 #=zLCVRNWs=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zA0pHDTueDwlCslT1lMvtrlY=(Boolean #=z0l0hrbY=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=z_ECPzXCcfqtBwTBtixDGIRz2fpFO7upc9cBXMcs=()
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=z6smfXzsslltCLAdzuDGsFfYxqXSdEy6v8jqnxBIhnGOD(Object[] #=z0l0hrbY=, Type[] #=zLCVRNWs=, Type[] #=zz4TzCJM=, Object[] #=zzMVPWH4=)
   at SX.#=qAbyGHcKjGnMRhl0jtZStdqZS7E0zYA$RozwpzYInurc=.#=zGFbV2XWrFAImcqidhm9$RVM=(Stream #=z0l0hrbY=, String #=zLCVRNWs=, Object[] #=zz4TzCJM=, Type[] #=zzMVPWH4=, Type[] #=zvHy_MUI=, Object[] #=zvpQtsdo=)
   at SX.#=zlRQlT$sBUkcFQKk16_vmkeYNQoz3Jf1vXXzQpO4=.#=zLu6RIdI=[T](String #=zJe7TqLY=)
   at SX.dje_zETGW42BG3Q3VJNJ87TYQLJERCHJJQNJC2MLWHW6S_ejd.#=zUgRVF0Z1OAZvwiFiA_UVARrgdAw4()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at (Object , Action )
   at SX.SX_'M.SX_!(Object G#, Action G$)
   at SX.dje_zETGW42BG3Q3VJNJ87TYQLJERCHJJQNJC2MLWHW6S_ejd.dje_z57WYATSZUD7R9M2_ejd()
   at Synapse_UI_Concept.Controls.AceEditor.#=zxq5lbMKPWGf$jrYRoOwFB24=(Object #=zfq2DB8s=, LoadingStateChangedEventArgs #=z3pM_BN4=)
   at CefSharp.Wpf.ChromiumWebBrowser.CefSharp.Internals.IWebBrowserInternal.SetLoadingStateChange(LoadingStateChangedEventArgs args)
   at CefSharp.Internals.ClientAdapter.OnLoadingStateChange(ClientAdapter* , scoped_refptr<CefBrowser>* browser, Boolean isLoading, Boolean canGoBack, Boolean canGoForward)

**Comment by Jmodel10** [comment]
can someone please tell me how to fix this, my synapse was working fine earlier today. I turned off my computer for a few seconds then came back and it was all messed up
