### ISSUE TITLE
Synapse wont start/input

### ISSUE THREAD

**Issue by kinzero** [LoukaMB/SynapseX#158]
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SX.SX_$(.SX_!(Object 5?)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zs5dSn0yMvn8yu0xsWWzK8ij8K_mgsf$KZFHOnNs=(Exception #=zAomKpw8=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zaQvztUwexplxk_aRF54RUJ0=(Object #=zAomKpw8=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zaNVs10G7w6QL3ISEZuxTN0I=(MethodBase #=zAomKpw8=, Boolean #=zjzFg4mA=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zjjk0kNe4riHXEVMbWUVI1carjoEEZoSuCbqjUrA=(#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74= #=zAomKpw8=, #=qaF9gLVahOlo4deWC7KlcayUqZahw3Ec69n0LjVWTtjE= #=zjzFg4mA=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zB6UMAfuBMgAmkTFZf8QwV6TKI17dos76YyLJHc0=()
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zvIY2P5eeBMlgYF3yLhpgVmE=(Boolean #=zAomKpw8=)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SX.SX_$(.SX_!(Object 5?)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zs5dSn0yMvn8yu0xsWWzK8ij8K_mgsf$KZFHOnNs=(Exception #=zAomKpw8=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zaQvztUwexplxk_aRF54RUJ0=(Object #=zAomKpw8=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zMXN5P3QGv5gVeMkgzgwU6yU=()
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zMgP4j7p6bmtAipre8NtAgVM=(Object #=zAomKpw8=, UInt32 #=zjzFg4mA=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zvIY2P5eeBMlgYF3yLhpgVmE=(Boolean #=zAomKpw8=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zHOqfGjxQWjQk8W9zqkb1pgDAp6u4n6VdoYzIe9s=()
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=z5X1ZzAuC4mXBsnz4tFUL8aBDrPXNEfJAw44FQxrIIooT(Object[] #=zAomKpw8=, Type[] #=zjzFg4mA=, Type[] #=zvejALbA=, Object[] #=zqudj0QU=)
   at SX.#=qi4NiAE3LTHtpaVpQH9y62iiapQmU1X2YG5IPOIR$G74=.#=zSMUD23r3l$J9BYzitQQxY2k=(Stream #=zAomKpw8=, String #=zjzFg4mA=, Object[] #=zvejALbA=, Type[] #=zqudj0QU=, Type[] #=zg5j9WJ0=, Object[] #=zTz$WwRo=)
   at SX.#=zGwbp1eiQhewNMx$EK8t5OtOTPxkRUD51qAxQmlQ=.#=zgf6pq3k=[T](String #=z_XC35s4=)
   at SX.dje_zEBQ3HB2LHR56TXTL9EKXEYSUGUUSGTSWQEYTKYA6_ejd.#=ztKKecolO3Gi_GR2zhRRrLYaaFAMd()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at (Object , Action )
   at SX.SX_''.SX_!(Object E&, Action E')
   at SX.dje_zEBQ3HB2LHR56TXTL9EKXEYSUGUUSGTSWQEYTKYA6_ejd.dje_z5Q89RP9GMBSL4VQ_ejd()
   at Synapse_UI_Concept.Controls.AceEditor.#=z6bebYh9bRE3zpkLPc2poMHw=(Object #=zxkDaGYQ=, LoadingStateChangedEventArgs #=zoYjrEzs=)
   at CefSharp.Wpf.ChromiumWebBrowser.CefSharp.Internals.IWebBrowserInternal.SetLoadingStateChange(LoadingStateChangedEventArgs args)
   at CefSharp.Internals.ClientAdapter.OnLoadingStateChange(ClientAdapter* , scoped_refptr<CefBrowser>* browser, Boolean isLoading, Boolean canGoBack, Boolean canGoForward)

**Comment by NikitaPlayer** [comment]
same
