### ISSUE TITLE
Error every time i open SynapseX 

### ISSUE THREAD

**Issue by Aflix-Discord** [LoukaMB/SynapseX#250]
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\Documents\Synapse X v1.0.0\auth\options.bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SX.SX_(9.SX_!(Object !";)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zFIITi2JtEECcJGgGudPfpWicN_6l(Exception #=zJOpB3$U=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zy1Z1tZuIbpVSP5ZnY2OrDu$Zrc8TD_gKDfJdi_U=(Object #=zJOpB3$U=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=za_6LKFHYkv0SSYUOtGr5Qu6fdr$cVfQCqA==(MethodBase #=zJOpB3$U=, Boolean #=ztEhm1s0=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zZcmw$BxEhcSGnVtTrTbQq8hkUBrwLDXRug==(#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc= #=zJOpB3$U=, #=qjs7hcMS3EnzrQ94rnv1lAMtTomrvAP4vqQf$Lp$W24Y= #=ztEhm1s0=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zEnK4hrhFQKsUSvQYcCBnrm_R148IDiqXK4Bs9GENjvgO()
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zxRInS5lBwHqedrPUaPCtb26nT1GK(Boolean #=zJOpB3$U=)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SX.SX_(9.SX_!(Object !";)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zFIITi2JtEECcJGgGudPfpWicN_6l(Exception #=zJOpB3$U=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zy1Z1tZuIbpVSP5ZnY2OrDu$Zrc8TD_gKDfJdi_U=(Object #=zJOpB3$U=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zn6_G_4OXNl6_MUQny5gnttAFGFSzxDZj1qPkJLhjKYIw()
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=z7TjycaUV3lmRgP6OweQbVvIbik$l(Object #=zJOpB3$U=, UInt32 #=ztEhm1s0=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zxRInS5lBwHqedrPUaPCtb26nT1GK(Boolean #=zJOpB3$U=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zSLenxpzJs0E$yFlSpMJf_OoTf7RpOmdnZBEvlNR3b1OD()
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zKP4wNIpHE6ivVX6jVrTV4TJJ5iHnWCCwZ6NYaBXlzxb9(Object[] #=zJOpB3$U=, Type[] #=ztEhm1s0=, Type[] #=zhB03vjY=, Object[] #=z2Hs$96c=)
   at SX.#=qhLLuXDLyDrMIssTa6Xq_7lU3$yjdgp1aZDzEe1iBJDc=.#=zSctphbTiBMd_ZSrHYU18wl45kB5yErNVbs_90umPp4t$(Stream #=zJOpB3$U=, String #=ztEhm1s0=, Object[] #=zhB03vjY=, Type[] #=z2Hs$96c=, Type[] #=zmfopRrk=, Object[] #=zLzKsG98=)
   at SX.#=z5ju6tzzLL8HGtFip3i2F4eEtQh_iJOQFUJdg09k=.#=z0XNScBE=[T](String #=zzYdrxy4=, T #=z9vZhWCM=)
   at SX.dje_zJQS9EGHM4385NUG7WW5MRBJED9BWRJEQ7A2TW824_ejd.#=zwLRRI1iJ23S0WV6xNw7wpxY=.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at (Object )
   at SX.SX_1\*.SX_!(Object "%])
   at SX.dje_zF92D8MBYE56ZWDX39XTTP5WXRUEJX2QJU6NX9MCG_ejd.Main()

**Comment by vaodaa** [comment]
A counselor put your email to your tickets is how they managed to help me.

**Comment by Aflix-Discord** [comment]
?
