### ISSUE TITLE
Need help this message keeps popping up and i cant open synapse

### ISSUE THREAD

**Issue by Krisjay4** [LoukaMB/SynapseX#301]
System.Exception: Unable to execute javascript at this time, scripts can only be executed within a V8Context. Use the IWebBrowser.CanExecuteJavascriptInMainFrame property to guard against this exception. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript for more details on when you can execute javascript. For frames that do not contain Javascript then no V8Context will be created. Executing a script once the frame has loaded it's possible to create a V8Context. You can use browser.GetMainFrame().ExecuteJavaScriptAsync(script) or browser.GetMainFrame().EvaluateScriptAsync to bypass these checks (advanced users only).
   at CefSharp.WebBrowserExtensions.EvaluateScriptAsync(IWebBrowser browser, String script, Nullable`1 timeout)
   at SX.SX_)t.SX_!(IWebBrowser Rk, String Rl, Nullable`1 Rm)
   at Synapse_UI_Concept.Controls.AceEditor.#=z2mJcfGZxk1ku(String #=zZ5cTXSk=)
   at Synapse_UI_Concept.Controls.AceEditor.#=zW6JfG5Q=()
   at SX.dje_zGLRDAARMMC28ZEJ9DEWLF7ZDF8ZSAFXAQ496VGTG_ejd.#=zziwXOh4_8hXRZdk6l1ggDDI=()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at (Object , Action )
   at SX.SX_').SX_!(Object E+, Action E,)
   at SX.dje_zGLRDAARMMC28ZEJ9DEWLF7ZDF8ZSAFXAQ496VGTG_ejd.#=zRmt$3F0ss8eG()
   at SX.dje_zGLRDAARMMC28ZEJ9DEWLF7ZDF8ZSAFXAQ496VGTG_ejd.#=zb3Lp0VRoJoUHQ2hfOYphWCU=()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by chxtwins** [comment]
have you tried turning off your antivirus
