### ISSUE TITLE
Synapse Issues.

### ISSUE THREAD

**Issue by Littlepman626** [LoukaMB/SynapseX#357]
Hey there synapse team!
i was setting up my synapse download after resetting my pc when i logged in and it came to an issue of cannot download because of a antivirus problem, ( All deactivated and everything ) or it would come up as a code. i couldnt contact you in the discord because i lost it of the other 50 discords i have so heres the error i get,

System.DllNotFoundException: Unable to load DLL 'SynapseInjector.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SYNX.#=zc$dmqNc46yYQvcNeZuGB2sd74BDm1sDt0g==.#=zyybmdgcNv_fi(UInt32 #=zEKa0q7U=, Byte[] #=zLFTSM1c=, Int32 #=za$nrAQo=)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SYNX.SYNX_؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٣ڤ.؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٢ٍ(Object )
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zvmHES5_vPSQVwjF3smiIOwo=(Exception #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z_XCGeZpvQb78wP7QSA==(Object #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zB4W$noOcMy9jZSThPalSSe7lYrWjZqbUGQD2UB6q93bo(MethodBase #=z00rS44o=, Boolean #=zddc8ZaM=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zm11vSehOAnol3HXPiJoYe2$vn3JzuF7F7IQ5pZYUDAAh(#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U= #=z00rS44o=, #=qpklSNsbdhoHxy4$nIDI2bug9srZjlphAKlBga7KBh7Y= #=zddc8ZaM=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zm_UZN4BDB6uCta$0A5I5sX4Ud7ejtXtRLsfzKTQhTU3t()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zxCHlDGokIhgzmo5Dwkg5XG00Znrt5PZnRBX7NYidJGj$(Boolean #=z00rS44o=)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SYNX.SYNX_؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٣ڤ.؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٢ٍ(Object )
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zvmHES5_vPSQVwjF3smiIOwo=(Exception #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z_XCGeZpvQb78wP7QSA==(Object #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zB0jvv4KHUzEpiXBV3pP9wGVBwvcIJBHz8A==()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z5TxVAOR6E7WV0brzqzyllKrd8GOv(Object #=z00rS44o=, UInt32 #=zddc8ZaM=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zxCHlDGokIhgzmo5Dwkg5XG00Znrt5PZnRBX7NYidJGj$(Boolean #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z2EyFrFCC2b8ZzUM219ZmVr0zVzm223ZYpkA2YFs=()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z_cOXeGJiHNV8IpidItNkVDA=(Object[] #=z00rS44o=, Type[] #=zddc8ZaM=, Type[] #=zesCwwRI=, Object[] #=z_1Zbims=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zVqlta9T07OsoATcRCvr70Xh2S3Ks$2V$WfynFZ4=(Stream #=z00rS44o=, Int32 #=zddc8ZaM=, Object[] #=zesCwwRI=, Type[] #=z_1Zbims=, Type[] #=zhNZSthw=, Object[] #=zxtvLFEk=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zrynh_$LKi8HR4I2fvuAKDyw=(Int32 #=z00rS44o=, Type[] #=zddc8ZaM=, Type[] #=zesCwwRI=, Boolean #=z_1Zbims=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zdJSU9mpbCCbqP7hm4xrZYLI=(#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U= #=z00rS44o=, #=qpklSNsbdhoHxy4$nIDI2bug9srZjlphAKlBga7KBh7Y= #=zddc8ZaM=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zm_UZN4BDB6uCta$0A5I5sX4Ud7ejtXtRLsfzKTQhTU3t()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zxCHlDGokIhgzmo5Dwkg5XG00Znrt5PZnRBX7NYidJGj$(Boolean #=z00rS44o=)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SYNX.SYNX_؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٣ڤ.؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٢ٍ(Object )
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zvmHES5_vPSQVwjF3smiIOwo=(Exception #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z_XCGeZpvQb78wP7QSA==(Object #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zB0jvv4KHUzEpiXBV3pP9wGVBwvcIJBHz8A==()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z5TxVAOR6E7WV0brzqzyllKrd8GOv(Object #=z00rS44o=, UInt32 #=zddc8ZaM=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zxCHlDGokIhgzmo5Dwkg5XG00Znrt5PZnRBX7NYidJGj$(Boolean #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z2EyFrFCC2b8ZzUM219ZmVr0zVzm223ZYpkA2YFs=()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z_cOXeGJiHNV8IpidItNkVDA=(Object[] #=z00rS44o=, Type[] #=zddc8ZaM=, Type[] #=zesCwwRI=, Object[] #=z_1Zbims=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zVqlta9T07OsoATcRCvr70Xh2S3Ks$2V$WfynFZ4=(Stream #=z00rS44o=, Int32 #=zddc8ZaM=, Object[] #=zesCwwRI=, Type[] #=z_1Zbims=, Type[] #=zhNZSthw=, Object[] #=zxtvLFEk=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zrynh_$LKi8HR4I2fvuAKDyw=(Int32 #=z00rS44o=, Type[] #=zddc8ZaM=, Type[] #=zesCwwRI=, Boolean #=z_1Zbims=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zMTDxkuaudQepCa9wPr6uOYi6vKBD(#=qHVOXEkr5705yv4Lpe_IcLzJfarc78RysG73M6jxeCsc= #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zdJSU9mpbCCbqP7hm4xrZYLI=(#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U= #=z00rS44o=, #=qpklSNsbdhoHxy4$nIDI2bug9srZjlphAKlBga7KBh7Y= #=zddc8ZaM=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zm_UZN4BDB6uCta$0A5I5sX4Ud7ejtXtRLsfzKTQhTU3t()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zxCHlDGokIhgzmo5Dwkg5XG00Znrt5PZnRBX7NYidJGj$(Boolean #=z00rS44o=)
--- End of stack trace from previous location where exception was thrown ---
   at (Object )
   at SYNX.SYNX_؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٣ڤ.؛۶ڿ۴ٗ؅۪؀ؾڷ۹ڍۛۛ٢ٍ(Object )
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zvmHES5_vPSQVwjF3smiIOwo=(Exception #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z_XCGeZpvQb78wP7QSA==(Object #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zB0jvv4KHUzEpiXBV3pP9wGVBwvcIJBHz8A==()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z5TxVAOR6E7WV0brzqzyllKrd8GOv(Object #=z00rS44o=, UInt32 #=zddc8ZaM=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=zxCHlDGokIhgzmo5Dwkg5XG00Znrt5PZnRBX7NYidJGj$(Boolean #=z00rS44o=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z2EyFrFCC2b8ZzUM219ZmVr0zVzm223ZYpkA2YFs=()
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z_cOXeGJiHNV8IpidItNkVDA=(Object[] #=z00rS44o=, Type[] #=zddc8ZaM=, Type[] #=zesCwwRI=, Object[] #=z_1Zbims=)
   at SYNX.#=qnmN7h8oZ3bTI3DacirhP7Oxe2bxumecRJWr7tSoGv4U=.#=z5LwObQekXD$IhQFcXCsZQG38sCudPziH4yptXQo=(Stream #=z00rS44o=, String #=zddc8ZaM=, Object[] #=zesCwwRI=, Type[] #=z_1Zbims=, Type[] #=zhNZSthw=, Object[] #=zxtvLFEk=)
   at SYNX.#=ziBXH_tNXp3nnFrCRRZYfKjkN$tSOivddIw==.#=z41QKWG0=[T](String #=zgjF2dhM=, T #=zLFTSM1c=)
   at SYNX.dje_zJ3P8ZQUM3UXH4SK92TL62P5ACWF9RUT6NZ_ejd.#=z2BaMHnh5jvrN(Object #=znCtglZo=, RoutedEventArgs #=zhNZSthw=)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by Noah3678** [comment]
same happens to me when i try to open on my acer
